version: '3.7'

services:
  backend-server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./env/.env:/boss-raid/env/.env
      - ./src:/boss-raid/src
    ports:
      - 3000:3000

  database-server:
    # platform: linux/x86_64 # 윈도우 환경에 설치된 도커를 쓰신다면 이부분을 제외해주세요!
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'boss-raid'
      MYSQL_ROOT_PASSWORD: '2222'
      MYSQL_TCP_PORT: 3308
      TZ: 'Asia/Seoul'
    command:
      [
        'mysqld',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
        '--default-time-zone=+09:00',
        '--default-authentication-plugin=mysql_native_password',
      ]
    ports:
      - 3308:3308

  redis-server:
    image: redis:latest
    ports:
      - 6379:6379
